<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Login' => 'Войти',
    'Profile' => 'Профиль',
    'Email' => 'Email',
    'Message' => 'Сообщение',
    'Username' => 'Имя пользователя',
    'Users' => 'Пользователи',
    'Reset your password' => 'Сбросить пароль',
    'Remember me' => 'Запомнить меня',
    'Password' => 'Пароль',
    'New password' => 'Новый пароль',
    'Current password' => 'Текущий пароль',
    'Sign in' => 'Войти',
    'Save' => 'Сохранить',
    'Subject' => 'Тема',
    'Submit' => 'Отправить',
    'Logout' => 'Выйти',
    'This username has already been taken.' => 'Это имя пользователя уже существует.',
    'This email address has already been taken.' => 'Этот адрес электронной почты уже существует.',
    'Your account details have been updated' => 'Настройки аккаунта были изменены',
    'An error occurred. Please try again later.' => 'Произошла ошибка. Пожалуйста, попробуйте позже.',
];
